name: Metrics (private-inclusive)

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: petopagi
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          filename: assets/metrics.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 10

      - name: Commit updated metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): update metrics (private-inclusive)"
          file_pattern: assets/metrics.svg


